# This workflow runs the script which populates the database with the JSON data from /setup_db/moviedata.json
# This workflow could be automated as part of CI/CD, but it's manually triggered for now.

name: Setup Database
on:
  workflow_dispatch:
jobs:
  create:
    name: Setup Database
    runs-on: ubuntu-latest
    steps:
      # Note, Python & pip are pre-installed on GH Runners
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install Boto3
        run: python -m pip install boto3

      - name: Checkout Master Branch
        uses: actions/checkout@master
      
      - name: Populate DB
        continue-on-error: false
        run: python db_setup/test.py
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_GH_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_GH_SECRET_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
